name: Build DLL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - arch: x86
            cmake_arch: Win32
          - arch: x64
            cmake_arch: x64

    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure & Generate (${{ matrix.arch }})
        run: |
          cmake -B build-${{ matrix.arch }} `
                -S . `
                -A ${{ matrix.cmake_arch }} `
                -D CMAKE_BUILD_TYPE=Release

      - name: Build (${{ matrix.arch }})
        run: |
          cmake --build build-${{ matrix.arch }} --config Release

      - name: Rename DLLs (${{ matrix.arch }})
        run: |
          Get-ChildItem -Path build-${{ matrix.arch }}\Release\*.dll | ForEach-Object {
            $new = "{0}.{1}{2}" -f $_.BaseName, "${{ matrix.arch }}", $_.Extension
            Rename-Item $_.FullName $new
          }

      - name: Upload artifacts (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: dll-debug-${{ matrix.arch }}
          path: build-${{ matrix.arch }}\Release\*.*
